const TOKEN_KEY='sentinel.token';
const GEO_URL='https://raw.githubusercontent.com/datasets/geo-countries/master/data/countries.geojson';
let scene,camera,renderer,globe,earth,stars,countryGroup,markerGroup,drag=false,px=0,py=0,autoRotate=true,selectedCountry=null,selectedIndex=0;
const demoRegions=[
{name:'INDIA',activity:'Medium',events:'124',query:'India news live official'},
{name:'UNITED STATES',activity:'Low',events:'178',query:'United States news live official'},
{name:'GERMANY',activity:'Elevated',events:'96',query:'Germany news live official'},
{name:'JAPAN',activity:'Medium',events:'83',query:'Japan news live official'},
{name:'BRAZIL',activity:'Medium',events:'72',query:'Brazil news live official'},
{name:'SOUTH AFRICA',activity:'Medium',events:'61',query:'South Africa news live official'},
{name:'UNITED KINGDOM',activity:'Elevated',events:'74',query:'United Kingdom news live official'},
{name:'AUSTRALIA',activity:'Low',events:'45',query:'Australia news live official'}
];
function getToken(){let t=localStorage.getItem(TOKEN_KEY);if(!t){t=window.prompt('Enter SentinelScan bearer token:');if(t)localStorage.setItem(TOKEN_KEY,t.trim())}return t?t.trim():''}
async function api(path,opts={}){const token=getToken();const headers=new Headers(opts.headers||{});headers.set('Accept','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);if(opts.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const r=await fetch(path,{...opts,headers});const type=r.headers.get('content-type')||'';if(!r.ok){const m=type.includes('json')?JSON.stringify(await r.json()):await r.text();throw Error(`${r.status}: ${m}`)}return type.includes('json')?r.json():r.text()}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function latLon(lat,lon,r=2.2){const p=THREE.MathUtils.degToRad(lat),q=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(r*Math.cos(p)*Math.cos(q),r*Math.sin(p),-r*Math.cos(p)*Math.sin(q))}
function polygonPoints(coords,r=2.205){return coords.map(([lon,lat])=>latLon(lat,lon,r))}
function addLine(coords,group){if(coords.length<2)return;const pts=polygonPoints(coords);const geo=new THREE.BufferGeometry().setFromPoints(pts);const mat=new THREE.LineBasicMaterial({color:0x2e7da7,transparent:true,opacity:.7});const line=new THREE.Line(geo,mat);line.userData.country=selectedCountry;group.add(line)}
function countryName(f){const p=f.properties||{};return p.ADMIN||p.NAME||p.name||p.NAME_EN||'UNKNOWN COUNTRY'}
function buildCountryFeature(feature,index){const group=new THREE.Group();const name=countryName(feature);group.userData={country:name,index};const g=feature.geometry;if(!g)return group;if(g.type==='Polygon'){g.coordinates.forEach(r=>addLine(r,group))}else if(g.type==='MultiPolygon'){g.coordinates.forEach(poly=>poly.forEach(r=>addLine(r,group)))}
// country centroid from bounding box, good enough for clickable marker
let minLon=180,maxLon=-180,minLat=90,maxLat=-90;const scanCoords=(a)=>{if(Array.isArray(a[0]))a.forEach(scanCoords);else{minLon=Math.min(minLon,a[0]);maxLon=Math.max(maxLon,a[0]);minLat=Math.min(minLat,a[1]);maxLat=Math.max(maxLat,a[1])}};scanCoords(g.coordinates);if(isFinite(minLon)){const pos=latLon((minLat+maxLat)/2,(minLon+maxLon)/2,2.22);const s=new THREE.Mesh(new THREE.SphereGeometry(.026,8,8),new THREE.MeshBasicMaterial({color:0x62e6bf}));s.position.copy(pos);s.userData={country:name,index};group.add(s)}countryGroup.add(group);return group}
async function loadCountries(){try{const r=await fetch(GEO_URL);if(!r.ok)throw Error(`country data ${r.status}`);const data=await r.json();countryGroup=new THREE.Group();countryGroup.name='COUNTRY_BOUNDARIES';scene.add(countryGroup);data.features.forEach((f,i)=>buildCountryFeature(f,i));document.getElementById('countryCount').textContent=data.features.length;setSelectedCountry(data.features.findIndex(f=>countryName(f).toUpperCase().includes('INDIA'))>=0?data.features.findIndex(f=>countryName(f).toUpperCase().includes('INDIA')):0,data.features);return data}catch(e){console.error('Country layer failed',e);document.getElementById('countryCount').textContent='—';return null}}
function setSelectedCountry(index,data){if(!data||!data[index])return;selectedIndex=index;selectedCountry=data[index];const name=countryName(selectedCountry);const d=demoRegions.find(x=>x.name===name.toUpperCase())||demoRegions.find(x=>x.name.includes(name.toUpperCase())||name.toUpperCase().includes(x.name));document.getElementById('countryName').textContent=name.toUpperCase();document.getElementById('countryMeta').textContent='Country boundary loaded • click to inspect';document.getElementById('activity').textContent=d?.activity||'Monitored';document.getElementById('events').textContent=d?.events||'—';countryGroup?.traverse(o=>{if(o.material?.color){o.material.color.set(o.userData?.country===name?0x62e6bf:0x2e7da7);o.material.opacity=(o.userData?.country===name)?0.9:0.65}});}
function selectByName(name){if(!countryGroup)return;countryGroup.traverse(o=>{if(o.userData?.country===name){selectedCountry={properties:{ADMIN:name}};document.getElementById('countryName').textContent=name.toUpperCase();document.getElementById('countryMeta').textContent='Country selected from global boundary layer';}})}
function initGlobe(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,0,7.1);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.getElementById('scene').appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0x7bb8ff,1.1));const light=new THREE.PointLight(0x4ce4b8,5,20);light.position.set(3,2,5);scene.add(light);const blue=new THREE.PointLight(0x426cff,3,18);blue.position.set(-4,-2,3);scene.add(blue);
const glow=new THREE.MeshBasicMaterial({color:0x0b2f70,transparent:true,opacity:.35});earth=new THREE.Mesh(new THREE.SphereGeometry(2.17,64,64),glow);globe=new THREE.Group();globe.add(earth);scene.add(globe);const wire=new THREE.LineSegments(new THREE.WireframeGeometry(new THREE.SphereGeometry(2.2,32,16)),new THREE.LineBasicMaterial({color:0x2666a3,transparent:true,opacity:.42}));globe.add(wire);countryGroup=new THREE.Group();globe.add(countryGroup);
const sg=new THREE.BufferGeometry();const pts=[];for(let i=0;i<1800;i++){const rr=12+Math.random()*10, a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);pts.push(Math.sin(b)*Math.cos(a)*rr,Math.sin(b)*Math.sin(a)*rr,Math.cos(b)*rr)}sg.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));stars=new THREE.Points(sg,new THREE.PointsMaterial({color:0x8bbcff,size:.025,transparent:true,opacity:.7}));scene.add(stars);
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;autoRotate=false;px=e.clientX;py=e.clientY});window.addEventListener('pointerup',()=>drag=false);window.addEventListener('pointermove',e=>{if(!drag)return;globe.rotation.y+=(e.clientX-px)*.006;globe.rotation.x+=(e.clientY-py)*.004;globe.rotation.x=Math.max(-1.2,Math.min(1.2,globe.rotation.x));px=e.clientX;py=e.clientY});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();camera.position.z=Math.max(4.7,Math.min(10,camera.position.z+e.deltaY*.004))},{passive:false});renderer.domElement.addEventListener('click',onGlobeClick);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate();loadCountries()}
function onGlobeClick(e){if(drag)return;const rect=renderer.domElement.getBoundingClientRect();const m=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hits=ray.intersectObjects(countryGroup.children,true);if(hits.length){const g=hits[0].object;const name=g.userData?.country||g.parent?.userData?.country;if(name){selectByName(name);flashCountry(name)}}}
function flashCountry(name){countryGroup?.traverse(o=>{if(o.material?.color&&o.userData?.country===name){o.material.color.set(0x62e6bf);o.material.opacity=.95;setTimeout(()=>{o.material.color.set(0x2e7da7);o.material.opacity=.7},900)}})}
function animate(){requestAnimationFrame(animate);if(autoRotate)globe.rotation.y+=.0008;stars.rotation.y-=.00008;renderer.render(scene,camera)}
function watchNews(){const name=document.getElementById('countryName').textContent;const q=encodeURIComponent(`${name} official news live YouTube`);window.open(`https://www.youtube.com/results?search_query=${q}`,'_blank','noopener')}
function openAssessment(){document.getElementById('modal').classList.add('open')}
function closeAssessment(){document.getElementById('modal').classList.remove('open')}
function statusClass(s){s=String(s||'').toUpperCase();return s.includes('PASS')?'pass':s.includes('FAIL')?'fail':s.includes('REVIEW')?'review':s.includes('ERROR')?'error':'manual'}
function renderResults(data){const root=document.getElementById('scanResults');root.replaceChildren();const results=Array.isArray(data?.results)?data.results:Array.isArray(data?.findings)?data.findings:[];if(!results.length){root.innerHTML='<div class="muted">No automated results returned.</div>';return}results.forEach(x=>{const d=document.createElement('div');d.className='result';const top=document.createElement('div');top.className='result-top';top.innerHTML=`<b>${esc(x.id||x.title||'Security Control')}</b><span class="pill ${statusClass(x.status||x.verdict)}">${esc(x.status||x.verdict||'UNKNOWN')}</span>`;d.appendChild(top);const desc=document.createElement('div');desc.className='muted';desc.style.marginTop='6px';desc.textContent=x.title||x.description||x.message||'';d.appendChild(desc);const ev=document.createElement('div');ev.className='evidence';ev.textContent=`Expected: ${x.expected||'—'}\nActual: ${x.actual||'—'}\nEvidence SHA-256: ${x.evidence_sha256||x.evidence_hash||'—'}`;d.appendChild(ev);root.appendChild(d)})}
async function scan(){const btn=document.getElementById('scanBtn');const target=document.getElementById('target').value.trim();btn.disabled=true;btn.textContent='SCANNING…';document.getElementById('assessmentStatus').textContent='RUNNING';try{const d=await api('/api/check',{method:'POST',body:JSON.stringify({target})});renderResults(d);document.getElementById('assessmentStatus').textContent='COMPLETE'}catch(e){document.getElementById('scanResults').innerHTML=`<div class="result"><b>Assessment error</b><div class="evidence">${esc(e.message)}\n\nIf SentinelScan is deployed on Render, it cannot reach World Monitor running on your laptop. Run SentinelScan locally for the real localhost assessment.</div></div>`;document.getElementById('assessmentStatus').textContent='ERROR'}finally{btn.disabled=false;btn.textContent='START ASSESSMENT'}}
async function lab(action){try{const d=await api(`/api/lab/${action}`,{method:'POST',body:'{}'});document.getElementById('labResult').textContent=JSON.stringify(d,null,2)}catch(e){document.getElementById('labResult').textContent=e.message}}
function tick(){document.getElementById('time').textContent=new Date().toUTCString().replace(' GMT',' UTC');setTimeout(tick,1000)}
document.getElementById('newsBtn').addEventListener('click',watchNews);document.getElementById('openAssessment').addEventListener('click',openAssessment);document.getElementById('closeModal').addEventListener('click',closeAssessment);document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeAssessment()});document.getElementById('scanBtn').addEventListener('click',scan);document.getElementById('labRetestBtn').addEventListener('click',()=>lab('retest'));document.getElementById('labFixBtn').addEventListener('click',()=>lab('fix'));document.getElementById('labRegressionBtn').addEventListener('click',()=>lab('regression'));document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim().toUpperCase();if(q)selectByName(q)}});
initGlobe();tick();
